DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM tutorialText WHERE name = 'Competence in Client-Lawyer Relationship') THEN
        INSERT INTO tutorialText (name, subheading_one, subheading_two, paragraph_one, paragraph_two, conclusion, bulletpoint_one, bulletpoint_two) 
        VALUES ('Competence in Client-Lawyer Relationship', 'Example Scenario Involving Lawyer Alex', 'Application and Consequences of Rule', 'A lawyer is required to provide competent representation, which includes the necessary legal knowledge, skill, thoroughness, and preparation. This is essential in complex legal scenarios. Alex, a lawyer, is handling a challenging patent infringement case for a technology company. The case involves advanced technology and multiple patents, requiring specialized knowledge. These are key challenges for Alex:', 'According to the American Bar Associations Model Rule 1.1, lawyers must ensure competent representation. If Alex fails to meet these standards, the repercussions could include:', 'Adhering to the duty of competence under Model Rule 1.1 is fundamental in law practice, especially in specialized fields like patent law. Lawyers need to recognize their limitations and acquire necessary expertise or collaborate with experts to prevent negative impacts on both themselves and their clients.', '{"Technical Complexity: Alex lacks the specific technological expertise needed for understanding patent claims and prior art.", "Limited Experience in Patent Law: Alex''s background is mainly in corporate law, which doesn''t fully equip them for the specific demands of patent law."}', '{"Sanctions: The court might impose penalties for not fulfilling the duty of competence.", "Malpractice Claims: The client could allege that Alex''s inadequate representation led to financial damages."}');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM tutorialText WHERE name = 'Scope of Representation and Allocation of Authority') THEN
        INSERT INTO tutorialText (name, subheading_one, subheading_two, paragraph_one, paragraph_two, conclusion, bulletpoint_one, bulletpoint_two) 
        VALUES ('Scope of Representation and Allocation of Authority', 'Lawyer-Client Decision-Making in Legal Representation', 'Lawyer-Client Authority and Representation Scope', 'Model Rule 1.2 sets forth the principles guiding the lawyer-client relationship, focusing on decision-making authority and representation scope. Under this rule, a lawyer must comply with the clients decisions regarding the objectives of representation, provided they are within legal and ethical confines. This includes the clients prerogative in matters such as settling disputes or deciding on a trial strategy in criminal cases. The rule also permits lawyers to limit representation scope with informed client consent and forbids lawyers from assisting in illegal activities, while allowing discussion of legal consequences.', 'In a scenario where Attorney Emily represents Mark in a personal injury lawsuit, the application of Model Rule 1.2 becomes crucial. The case illustrates a conflict between Marks desire for a substantial trial and Emilys professional opinion favoring a settlement. Here, Emily must balance respecting Marks autonomy with her obligation to offer competent advice. She is faced with questions about overriding Mark’s decision, adhering to a potentially less beneficial trial strategy, ensuring Mark is fully informed, and considering whether to continue representation if Marks choices might harm his case. Emilys challenge is to navigate these issues while complying with Model Rule 1.2. Non-compliance could lead to ethical complaints, legal malpractice claims, disciplinary actions, and reputational damage. Therefore, Emilys approach should involve transparent and effective communication with Mark to ensure decisions align with his best interests and professional ethical standards.', '', '{"In a personal injury case scenario, Attorney Emily represents Mark, where they face a conflict over whether to settle or go to trial. Emily, adhering to professional ethics, must balance respecting Mark’s autonomy with her duty to offer competent advice. This involves advising him about the potential risks and benefits of each option. The rule permits Emily to suggest a compromise, like preparing for trial while exploring settlement options.", "Non-compliance with Model Rule 1.2 can lead to ethical complaints, legal malpractice claims, professional discipline, and reputational damage. Hence, Emily must effectively communicate with Mark, ensuring decisions are made collaboratively, aligning with both ethical standards and Mark’s best interests."}', '{"", ""}');
    END IF;
END $$;
