name: "Bundlewatch Github Action"

on:
  push:

jobs:
  bundlewatch:
    runs-on: ubuntu-latest
    env:
      BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2.3.1

    - name: Use Node.js
      uses: actions/setup-node@v2.0.0
      with:
        node-version: 14.4.0

    - run: npm install -g bundlewatch@0.2.6

    - working-directory: client-admin
      env:
        CI_BRANCH_BASE: patcon/bundlewatch-lint
      run: |
        npm install
        npm run build:webpack
        npx bundlewatch

