name: "Bundlewatch Github Action"

on:
  pull_request:
    types: [synchronize, opened]

jobs:
  bundlewatch:
    runs-on: ubuntu-latest
    env:
      # This should be secret, but don't care for now.
      # TODO: Regenerate at https://service.bundlewatch.io/setup-github
      BUNDLEWATCH_GITHUB_TOKEN: 7823e169232c4aaaf7407d05ad070fc36e2296e4

    steps:
    - uses: actions/checkout@v2.3.1

    - name: Use Node.js
      uses: actions/setup-node@v2.0.0
      with:
        node-version: 14.4.0

    - working-directory: client-admin
      run: |
        npm install
        npm run build:webpack

    - working-directory: client-admin
      run: npx bundlewatch
