name: "Bundlewatch Github Action"

on:
  pull_request:
    types: [synchronize, opened]

jobs:
  bundlewatch:
    runs-on: ubuntu-latest
    env:
      BUNDLE_ANALYZER_TOKEN: ${{ secrets.BUNDLE_ANALYZER_TOKEN }}

    steps:
    - uses: actions/checkout@v2.3.1

    - name: Use Node.js
      uses: actions/setup-node@v2.0.0
      with:
        node-version: 14.4.0

    - working-directory: client-admin
      run: |
        npm install
        npm run build:webpack
